sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t brinst07/docker-react-app -f dockerfile.dev .

script:
  - docker run -e CI=true brinst07/docker-react-app npm run test npm run test -- --coverage

after_success:
  - echo "test success"